apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: online-boutique-demo-project
  source:
    repoURL: https://github.com/Rubius/ArgoCD.git
    path: app-of-apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:  {}