apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-boutique-demo-ingress
  annotations: {}
spec:
  tls:
    - hosts:
      - "online-boutique-demo.dev.rubius.com"
      secretName: "online-boutique-demo.dev.rubius.com-tls"
  rules:
  - host: "online-boutique-demo.dev.rubius.com"
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
        pathType: ImplementationSpecific