apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: online-boutique-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
      - "online-boutique-demo.dev.rubius.com"
      secretName: "online-boutique-demo.dev.rubius.com-tls"
  rules:
  - host: "online-boutique-demo.dev.rubius.com"
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /